version: '3.8'

services:
  # API Gateway - Point d'entrée pour toutes les requêtes
  api-gateway:
    build:
      context: ./server/services/api-gateway
    container_name: cesi-eat-api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - livreur-service
      - restaurant-service
      - user-service
      - order-service
    networks:
      - cesi-eat-network
    environment:
      - NODE_ENV=production
      - PORT=5000
      - LIVREUR_SERVICE_URL=http://livreur-service:3001
      - RESTAURANT_SERVICE_URL=http://restaurant-service:3002
      - USER_SERVICE_URL=http://user-service:3003
      - ORDER_SERVICE_URL=http://order-service:3004

  # Service livreur
  livreur-service:
    build:
      context: ./server/services/livreur-service
    container_name: cesi-eat-livreur-service
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - cesi-eat-network
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGO_URI=mongodb://mongodb:27017/cesi-eat-livreur
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672

  # Service restaurant
  restaurant-service:
    build:
      context: ./server/services/restaurant-service
    container_name: cesi-eat-restaurant-service
    depends_on:
      - mongodb
      - rabbitmq
      - mysql
    networks:
      - cesi-eat-network
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGO_URI=mongodb://mongodb:27017/cesi-eat-restaurant
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=restaurant_db
      - DB_USER=restaurant_user
      - DB_PASSWORD=restaurant_password
      - JWT_SECRET=votresecretjwt

  # Service utilisateur
  user-service:
    build:
      context: ./server/services/user-service
    container_name: cesi-eat-user-service
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - cesi-eat-network
    environment:
      - NODE_ENV=production
      - PORT=3003
      - MONGO_URI=mongodb://mongodb:27017/cesi-eat-user
      - JWT_SECRET=votresecretjwt
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672

  # Service commande
  order-service:
    build:
      context: ./server/services/order-service
    container_name: cesi-eat-order-service
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - cesi-eat-network
    environment:
      - NODE_ENV=production
      - PORT=3004
      - MONGO_URI=mongodb://mongodb:27017/cesi-eat-order
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672

  # MongoDB - Base de données principale
  mongodb:
    image: mongo:latest
    container_name: cesi-eat-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - cesi-eat-network
    command: ["--noauth"]

  # RabbitMQ - Message broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: cesi-eat-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - cesi-eat-network

  # Service de logs
  log-service:
    build:
      context: ./server/services/log-service
    container_name: cesi-eat-log-service
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - cesi-eat-network
    environment:
      - NODE_ENV=production
      - PORT=3005
      - MONGO_URI=mongodb://mongodb:27017/cesi-eat-logs
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672

  # Front-end React
  frontend:
    build:
      context: ./client
    container_name: cesi-eat-frontend
    ports:
      - "80:80"
    depends_on:
      - api-gateway
    networks:
      - cesi-eat-network

  # MySQL - Base de données pour le service restaurant
  mysql:
    image: mysql:8.0
    container_name: cesi-eat-mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cesi-eat-network
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=restaurant_db
      - MYSQL_USER=restaurant_user
      - MYSQL_PASSWORD=restaurant_password
    command: --default-authentication-plugin=mysql_native_password

networks:
  cesi-eat-network:
    driver: bridge

volumes:
  mongodb_data:
  rabbitmq_data:
  mysql_data:
