services:
  # Frontend Service
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - BROWSER=none
      - REACT_APP_API_URL=http://localhost:4000
    depends_on:
      - nginx
    networks:
      - app-network

  # Nginx Service
  nginx:
    build: ./nginx
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
      - restaurant-service
      - client-service
      - delivery-service
    networks:
      - app-network

  # Authentication Service
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    depends_on:
      - auth-db-postgres
    environment:
      - DATABASE_URL=postgresql://auth_user:auth_password@auth-db-postgres:5432/auth_db
      - JWT_SECRET=your_secret_key_change_in_production
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Authentication Database (PostgreSQL)
  auth-db-postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_password
      - POSTGRES_DB=auth_db
    volumes:
      - auth-db-postgres-data:/var/lib/postgresql/data
      - ./auth-service/init-db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  # Restaurant Service
  restaurant-service:
    build: ./restaurant-service
    ports:
      - "5001:5001"
    depends_on:
      - restaurant-db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@restaurant-db:5432/restaurant
    networks:
      - app-network

  # Restaurant Database (PostgreSQL)
  restaurant-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restaurant
    volumes:
      - restaurant-db-data:/var/lib/postgresql/data
      - ./restaurant-service/init-db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  # Client Service
  client-service:
    build: ./client-service
    ports:
      - "5002:5002"
    depends_on:
      - client-db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@client-db:5432/client
    networks:
      - app-network

  # Client Database (PostgreSQL)
  client-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=client
    volumes:
      - client-db-data:/var/lib/postgresql/data
      - ./client-service/init-db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  # Delivery Service
  delivery-service:
    build: ./delivery-service
    ports:
      - "5003:5003"
    depends_on:
      - delivery-db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@delivery-db:5432/delivery
    networks:
      - app-network

  # Delivery Database (PostgreSQL)
  delivery-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=delivery
    volumes:
      - delivery-db-data:/var/lib/postgresql/data
      - ./delivery-service/init-db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  # Logs Database (MongoDB)
  logs-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - logs-db-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  auth-db-postgres-data:
  restaurant-db-data:
  client-db-data:
  delivery-db-data:
  logs-db-data: